# Generated by Django 2.1 on 2018-08-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('name_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currensy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_auto', models.DateTimeField(auto_now_add=True)),
                ('Z_report_501', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Z_report_502', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cashless', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cash_day_start', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cash_day_end', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.CharField(max_length=200)),
                ('sum_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count_currensy', models.IntegerField(default=0)),
                ('sum_Z_report', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sum_check', models.DecimalField(decimal_places=2, max_digits=5)),
                ('check_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Check')),
                ('currensy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Currensy')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.People')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Store'),
        ),
    ]
